apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Upstream controller bundle. Bump the tag to upgrade.
# https://github.com/bitnami-labs/sealed-secrets#kustomize
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.36.6/controller.yaml
