vector:
  role: Agent
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 0.0.0.0:8686
    sources:
      kubernetes_logs:
        type: kubernetes_logs
    sinks:
      victorialogs:
        type: elasticsearch
        inputs:
          - kubernetes_logs
        endpoints:
          - http://victorialogs-server.logging.svc:9428/insert/elasticsearch/
        mode: bulk
        api_version: v8
        query:
          _msg_field: message
          _time_field: timestamp
          _stream_fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
