apiVersion: v1
kind: Secret
metadata:
  name: restic-smb-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.smb.username | quote }}
  password: {{ .Values.smb.password | quote }}
