apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dha-kustomize
  namespace: argocd
spec:
  goTemplate: true
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "0"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "5"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "6"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "7"
  generators:
    - list:
        elements:
          # Kustomize-based components
          - name: external-snapshotter
            path: redbox-platform/base/storage/external-snapshotter
            namespace: kube-system
            wave: "0"
          - name: kubevirt
            path: redbox-platform/base/virtualization/kubevirt
            namespace: kubevirt
            wave: "5"
          - name: cdi
            path: redbox-platform/base/virtualization/cdi
            namespace: cdi
            wave: "5"
          - name: kubevirt-manager
            path: redbox-platform/base/virtualization/kubevirt-manager
            namespace: kubevirt-manager
            wave: "6"
          - name: multus-cni
            path: redbox-platform/base/virtualization/multus-cni
            namespace: kube-system
            wave: "5"
          - name: kubernetes-nmstate
            path: redbox-platform/base/virtualization/kubernetes-nmstate
            namespace: nmstate
            wave: "5"
          # Workloads
          - name: podinfo
            path: redbox-platform/base/apps/podinfo
            namespace: podinfo
            wave: "7"
  template:
    metadata:
      name: "kustomize-{{ .name }}"
      namespace: argocd
      labels:
        wave: "{{ .wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/damhau/talos-gitops.git  # CHANGEME
        targetRevision: main
        path: "{{ .path }}"
        kustomize:
          patches:
            - target:
                kind: Ingress
              patch: |-
                - op: replace
                  path: /spec/rules/0/host
                  value: "{{ .name }}.dha.dhconsulting.ch"
            - target:
                kind: IngressRoute
              patch: |-
                - op: replace
                  path: /spec/routes/0/match
                  value: "Host(`{{ .name }}.dha.dhconsulting.ch`)"
            - target:
                kind: CDI
                name: cdi
              patch: |-
                - op: replace
                  path: /spec/config/uploadProxyURLOverride
                  value: "https://cdi.dha.dhconsulting.ch"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: cdis.cdi.kubevirt.io
          jsonPointers:
            - /spec
        - group: kubevirt.io
          kind: KubeVirt
          jsonPointers:
            - /spec/configuration
            - /spec/customizeComponents
            - /spec/certificateRotateStrategy
            - /spec/workloadUpdateStrategy
            - /status
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
