apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  labels:
    app.kubernetes.io/name: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        disabled: false
        displayname: "Redbox Admin"
        password: "$2b$12$shUEUvv4MgnMVkDgkWc0IO3YYb7IJLHUAW7gREGmosfkCzspiWnE."
        email: "admin@{{ .Values.global.domain }}"
        groups:
          - admins
